POST http://localhost:3000/api/dashboards
Content-Type: application/json

{
  "air_temp": 25,
  "dni": 124,
  "ghi": 421,
  "period_end": "2023-12-12",
  "period": 1.00
}

###
GET http://localhost:3000/api/dashboards

###
GET http://localhost:3000/api/dashboards/6546875ee2164bd90831396c